language: go
go:
- '1.2'
- '1.3'
- '1.4'
- '1.5'
- 'tip'
sudo: true
before_install:
- ./travis-mecab-install.sh
- export CGO_LDFLAGS="`mecab-config --libs`"
- export CGO_CFLAGS="-I`mecab-config --inc-dir`"
