language: go
go:
- '1.2'
- '1.3'
- '1.4'
- '1.5'
- '1.6'
- '1.7'
- 'tip'
sudo: true
before_install:
- ./travis-mecab-install.sh
- export CGO_LDFLAGS="`mecab-config --libs`"
- export CGO_FLAGS="`mecab-config --inc-dir`"
